MODEL:
  TYPE: anynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  BLOCK_TYPE: res_bottleneck_block
  DEPTHS: [2, 7, 13, 1]
  WIDTHS: [224, 336, 672, 2240]
  STRIDES: [2, 2, 2, 2]
  BOT_MULS: [1.0, 1.0, 1.0, 1.0]
  GROUP_WS: [112, 168, 168, 112]