MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 23
  W0: 384
  WA: 82.5
  WM: 2.0
  GROUP_W: 128
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.05
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 64
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 50
NUM_GPUS: 1
OUT_DIR: .
