MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 23
  W0: 256
  WA: 70.0
  WM: 1.96
  GROUP_W: 128
  BOT_MUL: 2.0
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 512
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 400
NUM_GPUS: 1
OUT_DIR: .
