MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 18
  W0: 184
  WA: 63.0
  WM: 2.15
  GROUP_W: 64
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 512
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 400
NUM_GPUS: 8
OUT_DIR: .
