MODEL:
  TYPE: anynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  BLOCK_TYPE: res_bottleneck_block
  DEPTHS: [2, 4, 10, 2]
  WIDTHS: [72, 168, 320, 960]
  STRIDES: [2, 2, 2, 2]
  BOT_MULS: [1.0, 1.0, 1.0, 1.0]
  GROUP_WS: [24, 24, 40, 40]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.8
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 1024
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 800
NUM_GPUS: 8
OUT_DIR: .
