MODEL:
  TYPE: mbdynamicanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [1, 2, 2, 2]
  DEPTHS: [3, 4, 6, 3]
  WIDTHS: [256, 512, 1024, 2048]
  BOT_MULS: [0.25, 0.25, 0.25, 0.25]
  GROUP_WS: [64, 128, 256, 512]
DYNAMICANYNET:
  STEM_W: [64]
MBDYNAMICANYNET:
  DM_RANGE: [0.66, 1.0]
  WM_RANGE: [0.5, 1.0]
  N_BRANCH: 2
OPTIM:
  LR_POLICY: exp2
  BASE_LR: 0.2
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
  STEP: 2.4
  LR_MULT: 0.97
BN:
  ZERO_INIT_FINAL_GAMMA: True
  USE_PRECISE_STATS: False
TRAIN:
  DATASET: imagenet-tar
  IM_SIZE: 224
  BATCH_SIZE: 256
  ELASTIC_SIZE: 4
TEST:
  DATASET: imagenet-tar
  IM_SIZE: 256
  BATCH_SIZE: 200
NUM_GPUS: 4
OUT_DIR: .
